version: '3.8'
services:
 web:
   build:
     context: .
   container_name: voltbras_web
   # define ports 8080 and 9229 for the node.js server
   ports:
     - 8080:4000
     - 9229:9229
   # define port 8080 for the node.js server
   environment:
     - SERVER_PORT=8080
     - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017
   volumes:
     - ./:/code
   command: npm start

 mongo:
   image: mongo:4.2.8
   container_name: voltbras_mongodb
   # define port 27017 for te MongoDB server
   ports:
     - 27017:27017
   volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
 mongoclient:
   image: mongoclient/mongoclient:latest
   container_name: voltbras_mongoclient
   depends_on:
     - mongo
   # define port 3300 to run the Nosqlclient
   ports:
     - 3300:3000

volumes:
   mongodb:
   mongodb_config:
